// Portfolio data — single source of truth.
const PORTFOLIO = {
  name: 'Jeff Palmer',
  handle: 'jeffpalm',
  role: 'Application Architect',
  location: 'Dallas, TX',
  email: 'hire@jeffpalm.dev',
  github: 'github.com/jeffpalm',
  linkedin: 'linkedin.com/in/jeffpalmdev',
  current: {
    company: 'WTG Energy',
    title: 'Application Architect',
    since: '2026',
  },
  intro: [
    "I build enterprise systems that don't feel like enterprise systems.",
    'Currently the Application Architect at WTG Energy — owning Tier 1 systems through a company-wide digital transformation.',
    'Framework-agnostic — I pick up whatever the job needs and ship it.',
  ],
  about: {
    short:
      'Engineer who came up through the business side. I spent five years automating away inefficiency in automotive retail before formally training as a developer — which is why I think first about the workflow, then about the code.',
    long: [
      "I lead full-stack work across whatever stack the problem calls for — React, Angular, Blazor on the front; Node, NestJS, .NET, or Python on the back; AWS or Azure underneath. The framework is a tool, not an identity. I'm happiest when the problem is messy, the stakeholders are real, and the system has to keep running while I rewire it.",
      "Today I'm the technical authority for Product Engineering at WTG Energy, mid company-wide digital transformation. I own the architecture and delivery of our Tier 1 systems — a bespoke ETRM, a custom CRM — and the patterns, standards, and reusable templates the rest of the team builds on. AI-assisted development is my primary delivery method, not a side experiment: I architect for AI leverage in the initial build and the maintenance after, and I design patterns that lower the skill barrier so business contributors can ship higher-quality apps on their own. The thing I care most about is right-sizing — knowing when a small internal tool just needs to ship fast, and when a Tier 1 system needs hardened patterns, security review, and foundations the whole team can reuse.",
      "I'm a Vim-and-tiling-WM person. I daily-drove Manjaro for years. I write small tools to remove friction from my own loop. I think a healthy dev culture is one where people teach each other on Tuesdays.",
      'Outside of work: chess, audio gear, and a long-running argument with myself about whether mechanical keyboards have peaked.',
    ],
  },
  work: [
    {
      id: 'wtg',
      year: '2026–',
      title: 'ETRM & CRM — Tier 1 Business Systems',
      org: 'WTG Energy',
      role: 'Application Architect',
      blurb:
        'Technical authority for Product Engineering during a company-wide digital transformation. Primary builder on a bespoke ETRM and custom CRM, and author of the patterns, standards, and reusable templates the whole team builds on — with AI-assisted development as the primary delivery method.',
      stack: [
        'AI-assisted development',
        'Architecture & standards',
        'Security review',
        'Tier 1 delivery',
      ],
      stackLabel: 'focus',
      confidential: true,
    },
    {
      id: 'nova',
      year: '2025–26',
      title: 'NOVA — Document Management Platform',
      org: 'IBM · NextEra Energy (ETRM)',
      role: 'Lead Full-Stack Developer',
      blurb:
        'Lead full-stack on an internal ETRM platform that links external documents to Openlink trading objects.',
      stack: [
        'React 19',
        'React Router v7',
        'Tailwind 4',
        'NestJS',
        'Python λ',
        'DynamoDB',
        'Kafka/MSK',
        'AWS CDK',
      ],
      metrics: [
        { k: '93/122', v: 'webapp commits' },
        { k: '99%', v: 'lambda test coverage' },
        { k: '4 envs', v: 'dev/sit/uat/prod' },
      ],
      confidential: true,
    },
    {
      id: 'etrm',
      year: '2025–26',
      title: 'ETRM Integration Middleware',
      org: 'IBM · NextEra Energy',
      role: 'Feature Lead',
      blurb:
        'Authored the NOVA→Documentum integration end-to-end and co-led the DMI lambda migration into a shared CDK monorepo.',
      stack: ['Python', 'AWS CDK', 'Kafka', 'CloudFormation', 'SQL Server', 'Bash'],
      metrics: [
        { k: '11+', v: 'GitHub Actions' },
        { k: '4', v: 'repos shipped' },
      ],
      confidential: true,
    },
    {
      id: 'tag',
      year: '2024–25',
      title: 'Ava — Property Tax Platform',
      org: 'Dialexa · Tax Advisors Group',
      role: 'Senior Software Developer',
      blurb:
        "Next-gen platform powering ~30% of TAG's revenue. Built the Freeport Tax Exemption flow end-to-end and a live-debugging tool that sped up QA dramatically.",
      stack: ['.NET', 'Blazor', 'Azure'],
    },
    {
      id: 'deloitte',
      year: '2022–24',
      title: 'About Me — Global Tax',
      org: 'Dialexa · Deloitte',
      role: 'Senior Software Developer',
      blurb:
        '53 countries, 6 languages. Led the .NET Framework → .NET Core cloud-modernization effort and rebuilt conditional question logic as a dependency-graph pub/sub.',
      stack: ['Angular', '.NET Core', 'Azure'],
    },
    {
      id: 'covr',
      year: '2020–22',
      title: 'Covr — Workforce Platform',
      org: 'TrackNow / Covr',
      role: 'Full-Stack Engineer',
      blurb:
        'Modernized a legacy PHP monolith via the strangler pattern. Owned two features that drove a 50% increase in client base — a meal-break SMS tool and a Twilio-powered mass-messaging platform.',
      stack: [
        'React',
        'TypeScript',
        'NestJS',
        'Prisma',
        'Postgres',
        'PHP/Laravel',
        'Twilio',
        'Docker',
        'K8s',
      ],
    },
    {
      id: 'dvsafe',
      year: '2020',
      title: 'DV SAFE',
      org: 'Non-profit',
      role: 'Senior Front-End Developer',
      blurb:
        'Built the front-end for a non-profit that gives domestic-violence survivors a free, secure place to store evidence. Pro bono.',
      stack: ['React'],
      url: 'dvsafe.org',
    },
    {
      id: 'driversselect',
      year: '2015–20',
      title: 'driversselect Internal Platform',
      org: 'Sonic Automotive / EchoPark',
      role: 'Business Process & Systems Manager',
      blurb:
        'Where it started. Built the internal automation portal that saved $7.5M/yr, lifted salesperson efficiency 30%, and helped scale one location from 400 to 1,500 cars/month.',
      stack: ['Node', 'React', 'Postgres'],
      metrics: [
        { k: '$7.5M', v: 'annual savings' },
        { k: '+30%', v: 'sales efficiency' },
        { k: '400→1,500', v: 'cars/mo' },
      ],
    },
  ],
  experience: [
    {
      from: 'Jun 2026',
      to: 'Now',
      company: 'WTG Energy',
      title: 'Application Architect',
      note: 'Tier 1 systems · digital transformation',
    },
    {
      from: 'Feb 2025',
      to: 'Jun 2026',
      company: 'IBM',
      title: 'Senior Software Engineer',
      note: 'ETRM platform engineering',
    },
    {
      from: 'Jun 2022',
      to: 'Feb 2025',
      company: 'Dialexa (acquired by IBM)',
      title: 'Senior Software Engineer',
    },
    {
      from: 'Dec 2020',
      to: 'Jun 2022',
      company: 'Covr',
      title: 'Full-Stack Engineer',
    },
    {
      from: 'Nov 2020',
      to: 'Jan 2021',
      company: 'DV SAFE',
      title: 'Senior Front-End (pro bono)',
    },
    {
      from: 'Apr 2020',
      to: 'Jul 2020',
      company: 'DevMountain',
      title: 'Web Dev Cert · Best Overall Project',
    },
    {
      from: 'Sep 2015',
      to: 'Mar 2020',
      company: 'driversselect / Sonic',
      title: 'Business Process & Systems Manager',
    },
  ],
  skills: {
    Frontend: [
      'React',
      'React Router',
      'TypeScript',
      'TailwindCSS',
      'TanStack Query',
      'Angular',
      'Blazor',
      'Motion',
    ],
    Backend: ['Node.js', 'NestJS', 'Python', '.NET Core', 'Laravel', 'Express', 'Fastify'],
    Data: ['Postgres', 'DynamoDB', 'MySQL', 'Prisma', 'Redis', 'SQL Server'],
    'Cloud / Infra': [
      'AWS Lambda',
      'AWS CDK',
      'S3',
      'Kafka / MSK',
      'CloudFormation',
      'Cognito',
      'Docker',
      'Kubernetes',
    ],
    DX: ['Vim', 'Git', 'GitHub Actions', 'SonarQube', 'Husky', 'Linux (Manjaro)'],
  },
  loves: [
    'Vim',
    'Git',
    'Scripting & automation',
    'Regex',
    'Docker',
    'Linux',
    'Mechanical keyboards',
    'Chess',
    'A/V gear',
  ],
};

export default PORTFOLIO;
